"""initial_base

Revision ID: 2aa94ae571f8
Revises: 
Create Date: 2026-04-05 18:12:11.827285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa94ae571f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fitbit_access_token', sa.String(), nullable=True),
    sa.Column('fitbit_refresh_token', sa.String(), nullable=True),
    sa.Column('fitbit_user_id', sa.String(), nullable=True),
    sa.Column('fitbit_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('category', sa.String(), server_default='weighted', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_muscle_group'), ['muscle_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_user_id'), ['user_id'], unique=False)

    op.create_table('meso_cycles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meso_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meso_cycles_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('micro_cycles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meso_cycle_id', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meso_cycle_id'], ['meso_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), server_default='1', nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('meso_cycle_id', sa.String(), nullable=True),
    sa.Column('previous_weight', sa.Float(), nullable=True),
    sa.Column('average_rpe', sa.Float(), nullable=True),
    sa.Column('suggested_weight', sa.Float(), nullable=False),
    sa.Column('adjustment_reason', sa.Text(), nullable=False),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_rpe', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['meso_cycle_id'], ['meso_cycles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_logs_user_id'), ['user_id'], unique=False)

    op.create_table('plan_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_session_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_session_id'], ['plan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('meso_cycle_id', sa.String(), nullable=True),
    sa.Column('micro_cycle_id', sa.String(), nullable=True),
    sa.Column('plan_session_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.String(), nullable=True),
    sa.Column('actual_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meso_cycle_id'], ['meso_cycles.id'], ),
    sa.ForeignKeyConstraint(['micro_cycle_id'], ['micro_cycles.id'], ),
    sa.ForeignKeyConstraint(['plan_session_id'], ['plan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('sleep_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('fitbit_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('session_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('volume_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volume_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_history_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_history_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_history_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_exercise_id', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sets_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_sets_session_exercise_id'))

    op.drop_table('exercise_sets')
    with op.batch_alter_table('volume_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_volume_history_session_id'))
        batch_op.drop_index(batch_op.f('ix_volume_history_exercise_id'))

    op.drop_table('volume_history')
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercises_exercise_id'))

    op.drop_table('session_exercises')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_user_id'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_user_id'))

    op.drop_table('training_sessions')
    op.drop_table('plan_exercises')
    with op.batch_alter_table('suggestion_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_logs_user_id'))

    op.drop_table('suggestion_logs')
    op.drop_table('plan_sessions')
    op.drop_table('micro_cycles')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))

    op.drop_table('plans')
    with op.batch_alter_table('meso_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meso_cycles_user_id'))

    op.drop_table('meso_cycles')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_muscle_group'))

    op.drop_table('exercises')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
