"""add_created_at_and_cascade_updates

Revision ID: b61926268491
Revises: 2aa94ae571f8
Create Date: 2026-04-16 19:00:23.019589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b61926268491'
down_revision: Union[str, None] = '2aa94ae571f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sets_session_exercise_id'), ['session_exercise_id'], unique=False)
        batch_op.drop_constraint('exercise_sets_session_exercise_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session_exercises', ['session_exercise_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'weighted'::text"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_exercises_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.alter_column('fitbit_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_health_metrics_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('health_metrics_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('meso_cycles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_meso_cycles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('micro_cycles', schema=None) as batch_op:
        batch_op.drop_constraint('micro_cycles_meso_cycle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meso_cycles', ['meso_cycle_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.drop_constraint('plan_exercises_plan_session_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('plan_exercises_exercise_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'plan_sessions', ['plan_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plan_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('plan_sessions_plan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercises_session_id'), ['session_id'], unique=False)
        batch_op.drop_constraint('session_exercises_session_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('session_exercises_exercise_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'training_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('suggestion_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_suggestion_logs_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('suggestion_logs_meso_cycle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('suggestion_logs_exercise_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meso_cycles', ['meso_cycle_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('plan_session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_training_sessions_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('training_sessions_meso_cycle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('training_sessions_micro_cycle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('training_sessions_plan_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'micro_cycles', ['micro_cycle_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'plan_sessions', ['plan_session_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'meso_cycles', ['meso_cycle_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('fitbit_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('volume_history', schema=None) as batch_op:
        batch_op.alter_column('calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_volume_history_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_history_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_history_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('volume_history_session_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('volume_history_exercise_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'training_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('volume_history_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key('volume_history_session_id_fkey', 'training_sessions', ['session_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_volume_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_volume_history_session_id'))
        batch_op.drop_index(batch_op.f('ix_volume_history_exercise_id'))
        batch_op.alter_column('calculated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fitbit_token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('training_sessions_plan_session_id_fkey', 'plan_sessions', ['plan_session_id'], ['id'])
        batch_op.create_foreign_key('training_sessions_micro_cycle_id_fkey', 'micro_cycles', ['micro_cycle_id'], ['id'])
        batch_op.create_foreign_key('training_sessions_meso_cycle_id_fkey', 'meso_cycles', ['meso_cycle_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_training_sessions_user_id'))
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('plan_session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('suggestion_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('suggestion_logs_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key('suggestion_logs_meso_cycle_id_fkey', 'meso_cycles', ['meso_cycle_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_suggestion_logs_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('session_exercises_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key('session_exercises_session_id_fkey', 'training_sessions', ['session_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercises_exercise_id'))
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('plan_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plan_sessions_plan_id_fkey', 'plans', ['plan_id'], ['id'])

    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plan_exercises_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key('plan_exercises_plan_session_id_fkey', 'plan_sessions', ['plan_session_id'], ['id'])

    with op.batch_alter_table('micro_cycles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('micro_cycles_meso_cycle_id_fkey', 'meso_cycles', ['meso_cycle_id'], ['id'])

    with op.batch_alter_table('meso_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meso_cycles_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('health_metrics_session_id_fkey', 'training_sessions', ['session_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_health_metrics_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('fitbit_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'weighted'::text"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exercise_sets_session_exercise_id_fkey', 'session_exercises', ['session_exercise_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_exercise_sets_session_exercise_id'))

    # ### end Alembic commands ###
