"""initial_migration

Revision ID: de759b90bdc4
Revises: 
Create Date: 2026-04-05 17:33:37.502149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de759b90bdc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercise_sets_session_exercise_id'), 'exercise_sets', ['session_exercise_id'], unique=False)
    op.add_column('exercises', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_meso_cycles_user_id'), 'meso_cycles', ['user_id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_exercise_id'), 'session_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_index(op.f('ix_suggestion_logs_user_id'), 'suggestion_logs', ['user_id'], unique=False)
    op.add_column('training_sessions', sa.Column('plan_session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'training_sessions', 'plan_sessions', ['plan_session_id'], ['id'])
    op.create_index(op.f('ix_volume_history_exercise_id'), 'volume_history', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_volume_history_session_id'), 'volume_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_volume_history_user_id'), 'volume_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_history_user_id'), table_name='volume_history')
    op.drop_index(op.f('ix_volume_history_session_id'), table_name='volume_history')
    op.drop_index(op.f('ix_volume_history_exercise_id'), table_name='volume_history')
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_column('training_sessions', 'plan_session_id')
    op.drop_index(op.f('ix_suggestion_logs_user_id'), table_name='suggestion_logs')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_exercise_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_meso_cycles_user_id'), table_name='meso_cycles')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_column('exercises', 'user_id')
    op.drop_index(op.f('ix_exercise_sets_session_exercise_id'), table_name='exercise_sets')
    # ### end Alembic commands ###
